# Nascraft config.yml - ${project.version}

# Language file to use. Available: en_US es_ES
language: 'en_US'

database:
  # How many days should the trade's log last in the database?
  # With the option 60, all trades older than 60 days will be automatically removed.
  # Use -1 to disable (Keep all trades logged).
  days-until-history-removed: 60

price-options:
  # Set (hard) limits on the minimum and maximum prices.
  limits:
    low: 0.001
    high: 9999999
  # With noise enabled, prices will vary over time in a pseudo-random manner.
  noise:
    enabled: true
    # Change the default intensity of the noise with this factor.
    default-intensity: 1
  # The default elasticity applies to all items unless otherwise explicitly stated at items.yml.
  default-elasticity: 1

market-control:
  # Although taxation gets applied for buying and selling actions separately, the total tax paid is the same regardless of how it is split
  # The spread is determined by the deviation in both actions. In the default case, it is 6% for selling and 4% for buying, resulting in a total spread of 10%.

  # To avoid strengthening the underground economy, try to keep the taxation as low as possible.
  # Heavy taxation can encourage players to trade with each other directly, bypassing intermediaries,
  # and reducing the amount of money collected from taxes and making the market less efficient.
  #
  # This value will be applied by default if no other tax is explicitly stated on the item at items.yml
  taxation:
    # 6% taxation when players sell items.
    sell: 0.06
    # 4% taxation when players buy items.
    buy: 0.04
  # Do players need the permission "nascraft.market" to operate directly with commands?
  market-permission: true

commands:
  # Available commands: sell, sellall, sellhand
  enabled:
    - 'sell'
    - 'sellall'
    - 'sellhand'

placeholders:
  # Number of decimals to display in prices.
  # For instance, with a price of 2.2732:
  # 1 -> 2.3$
  # 2 -> 2.27$
  # 3 -> 2.273$
  decimal-precision: 2

# FEATURE IN BETA AS OF ${project.version}
# Use with caution.
discord-bot:
  enabled: false
  # Available methods: NATIVE, DISCORDSRV
  link-method: 'NATIVE'
  token: 'TOKEN-ID'
  channel: 'TEXTCHANNEL-ID'
  # Role requiered to execute admin commands through discord.
  # Current commands: /stop, /resume, /seeinv [ID], /seebal [ID]
  admin-role-id: 'ROLE-ID'
  # Default size of discord's virtual inventories.
  default-inventory: 5
  # Formula to calculate the price of then next slot. slot_price_factor * #slot + slot_price_base = price
  # For example, to buy the slot nº6 the price will be (1000 * 6) + 10000 = 16000$
  slot-price-factor: 1000
  slot-price-base: 10000
  # Discord taxes:
  taxation:
    override: true
    # By default, we apply a reduced tax to persuade users to operate through discord.
    buy: 0.04
    sell: 0.05

sell-wands:
  enabled: true
  wands:
    # ID - Just the identifier.
    basic:
      material: 'stick'
      display-name: '&a&lBASIC WAND'
      lore:
        - '&aRight-click &7to estimate value.'
        - '&cLeft-click &7a container to'
        - '&7sell all its content to the market!'
        - ' '
        - '&7Uses left: &6[USES]'
      # Maximum uses of the wand. Alternativelly you can place a limit on
      # the quantity of the sells. See "MILLONAIRE WAND".
      # If you don't set any of these, the wand can be used without limits. (See "PERMANENT WAND").
      uses: 10
      # Permission to use this specific wand. If not defined, no permission will be required.
      permission: 'nascraft.wand.basic'
    permanent:
      material: 'blaze_rod'
      enchanted: true
      display-name: '&d&lPERMANENT WAND'
      lore:
        - '&aRight-click &7to estimate value.'
        - '&cLeft-click &7a container to'
        - '&7sell all its content to the market'
        - '&7for &chalf &7its value.'
        - '&75 minutes of cooldown between uses.'
        - ' '
        - '&cUNLIMITED USES'
      multiplier: 0.5
      # Set a minimum cooldown between uses in seconds.
      cooldown: 300 # 300/60 = 5 min of cooldown.
      permission: 'nascraft.wand.advanced'
    millionaire:
      material: 'blaze_rod'
      enchanted: true
      display-name: '&6&lMILLONAIRE WAND'
      lore:
        - '&aRight-click &7to estimate value.'
        - '&cLeft-click &7a container to'
        - '&7sell all its content to the market'
        - '&7for &6x1.5 &7its value.'
        - ' '
        - '&7Left to sell: &a[PROFIT]'
      # With this wand you can sell a maximum of 1.000.000$ (Including the multiplier)
      max-profit: 1000000
      multiplier: 1.5
      permission: 'nascraft.wand.millonaire'

# Verify whether the AdvancedGUI's layout is present, and if it is not, place it in the layout folder of AdvancedGUI.
auto-resources-injection: true
