# Nascraft config.

# Check if the layout(s) required are present, and place them in case they are not.
AutoResourcesInjection: true

Items_quoted:
  Categories:
    # Name of the category. Categories are displayed in the main menu.
    1:
      # Display-name of the category.
      name: "Stone age"
      # Items of the category.
      items:
        # Material of the item.
        cobblestone:
          # INITIAL price. This value will be ignored once the market starts developing his own valuations.
          price: 1
          # Specify the trend of the item fluctuations (Only if random oscillations is enabled)
          # Available values: FLAT, BEAR1, BEAR2, BEAR3, BULL1, BULL2, BULL3
          trend: "BULL1"
          # child items. The price of these items will be determined by his parent item and vice versa.
          child:
            cobblestone_slab:
              # To make a cobblestone slab we only need half of a cobblestone, so the price of the slab is half the price of the cobblestone.
              # Result: (Price cobblestone)*0.5 - Hence, the initial price will be 0.5 for one slab.
              multiplier: 0.5
            cobblestone_stairs:
              # For a cobblestone stair we need 6 of cobblestone, while we only get 4 stairs. So, the price will be 6/4 = 3/2 = 1.5
              # Keep in mind that this logic is not necessary, as you could say that a stair costs x10 the price of cobblestone,
              # but that not only makes no sense, it would probably allow people to take advantage of these overvaluations.
              multiplier: 1.5
            cobblestone_wall:
              # Spends 6, gets 6. 6/6 = 1/1 = 1
              multiplier: 1
        stone:
          price: 1.5
          child:
            stone_stairs:
              multiplier: 1.5
            stone_slab:
              multiplier: 0.5
            stone_pressure_plate:
              multiplier: 2
            stone_button:
              multiplier: 1
        cobbled_deepslate:
          price: 0.7
          child:
            cobbled_deepslate_stairs:
              multiplier: 1.5
            cobbled_deepslate_slab:
              multiplier: 0.5
            cobbled_deepslate_wall:
              multiplier: 1
    # Another category.
    2:
      name: "Tech"
      items:
        redstone:
          price: 2
          child:
            redstone_block:
              multiplier: 9
        redstone_torch:
          price: 3
        repeater:
          price: 6
        comparator:
          price: 10
        piston:
          price: 9
        observer:
          price: 8
    3:
      name: "In the woods"
      items:
        oak_log:
          price: 1
          child:
            oak_planks:
              multiplier: 0.25
            oak_stairs:
              multiplier: 0.375
            oak_slab:
              multiplier: 0.125
            stick:
              multiplier: 0.0625
        birch_log:
          price: 1
          child:
            birch_planks:
              multiplier: 0.25
            birch_stairs:
              multiplier: 0.375
            birch_slab:
              multiplier: 0.125
            stick:
              multiplier: 0.0625
    4:
      name: "Valuables"
      items:
        diamond:
          price: 100
        emerald:
          price: 50
        raw_gold:
          price: 20
    5:
      name: "Utils"
      items:
        coal:
          price: 4
          child:
            charcoal:
              multiplier: 1
        leather:
          price: 10
    6:
      name: "Ingots"
      items:
        iron_ingot:
          price: 4
        copper_ingot:
          price: 3
        gold_ingot:
          price: 10
        netherite_ingot:
          price: 500

Price_options:
  # With random oscillation enabled prices will vary in time based on these settings:
  random_oscillation:
    enabled: true
    # Specify the general trend of the market (Only applied to items without a specified trend)
    # Available values: FLAT, BEAR1, BEAR2, BEAR3, BULL1, BULL2, BULL3
    market_trend: FLAT
  # Should prices be affected by buys / sells?
  supply_and_demand: true

Market_control:
  # Limit the precision of prices. With 2 the minimum price would be 0.01, with 3: 0.001 etc
  decimal_limit: 2
  limits:
    low: 0.01
    high: 99999
  # The spread is determined by the deviation in both actions. In the default case: 3% + 2% -> 5% of spread
  taxation:
    # 3% taxation when players sell items.
    sell: 0.03
    # 2% taxation when players buy items.
    buy: 0.02
  high_market_control:
    # Enable the /nascraft force <> subcommands:
    enabled: true
    # Wipe ~50% of the valuations in a couple of movements.
    force_crash: false
    # Pump a ~50% of the valuations in minutes
    force_bullrun: false
    # Set the general tendency of the oscillations to positive.
    force_bull: true
    # Set the general tendency of the oscillations to negative.
    force_bear: true

Lang:
  currency: "€"