# Nascraft config - 1.2.1

# Verify whether the required layout is present (and in the correct version), and if it is not, place it in the layout folder of AdvancedGUI.
auto_resources_injection: true

price_options:
  # Set limits on the minimum and maximum prices.
  limits:
    low: 0.05
    high: 999
  # With noise enabled, prices will vary over time in a pseudo-random manner.
  noise:
    enabled: true

market_control:
  # Although taxation is separated for buying and selling actions separately, the total tax paid is the same regardless of how it is split
  # The spread is determined by the deviation in both actions. In the default case, it is 6% for selling and 4% for buying, resulting in a total spread of 10%.

  # To avoid strengthening the underground economy, try to keep the taxation as low as possible.
  # Heavy taxation can encourage players to trade with each other directly, bypassing intermediaries,
  # and reducing the amount of money collected from taxes and making the market less efficient.
  taxation:
    # 6% taxation when players sell items.
    sell: 0.06
    # 4% taxation when players buy items.
    buy: 0.04
  # Do players need the permission "nascraft.market" to operate directly with commands?
  market_permission: true

commands:
  # Available commands: sell, sellall, sellhand
  enabled:
    - "sell"
    - "sellall"
    - "sellhand"
