# Nascraft config.

# Check if the layout(s) required are present, and place them in case they are not.
AutoResourcesInjection: true

Items_quoted:
  Categories:
    # Num of the category. Categories are displayed in the main menu.
    1:
      icon: "cobblestone"
      # Name of the category.
      name: "Stone age"
      # Number of individual items needed to fluctuate the price. Adjust for volatility.
      required_to_move: 64
      items:
        # Items of the category
        cobblestone:
          # INITIAL price. This value will be ignored once the market starts developing his own valuations.
          price: 1
          # child items. The price of this items will be determined by his parent item and vice versa.
          child:
            cobblestone_stairs:
              # this option will set the price of cobblestone stairs at 1.5 * (price of cobblestone).
              linked: 1.5
            cobblestone_slab:
              linked: 0.5
            cobblestone_wall:
              linked: 1
        stone:
          price: 1.5
          child:
            stone_stairs:
              linked: 1.5
            stone_slab:
              linked: 0.5
            stone_pressure_plate:
              linked: 2
            stone_button:
              linked: 1
        cobbled_deepslate:
          price: 0.7
          child:
            cobbled_deepslate_stairs:
              linked: 1.5
            cobbled_deepslate_slab:
              linked: 0.5
            cobbled_deepslate_wall:
              linked: 1
    2:
      icon: "redstone"
      name: "Tech"
      required_to_move: 16
      items:
        redstone:
          price: 2
          child:
            redstone_block:
              linked: 9
        redstone_torch:
          price: 3
        repeater:
          price: 6
        comparator:
          price: 10
        piston:
          price: 9
        observer:
          price: 8
    3:
      icon: "oak_planks"
      name: "In the woods"
      required_to_move: 16
      items:
        oak_log:
          price: 1
          child:
            oak_planks:
              linked: 0.25
            oak_stairs:
              linked: 1.5
            oak_slab:
              linked: 0.5
            stick:
              linked: 0.0625
        birch_log:
          price: 1
          child:
            birch_planks:
              linked: 0.25
            birch_stairs:
              linked: 1.5
            birch_slab:
              linked: 0.5
            stick:
              linked: 0.0625
    4:
      icon: "diamond"
      name: "Valuables"
      required_to_move: 16
      items:
        diamond:
          price: 100
        emerald:
          price: 50
        raw_gold:
          price: 20
    5:
      icon: "coal"
      name: "Utils"
      required_to_move: 16
      items:
        coal:
          price: 4
          child:
            charcoal:
              linked: 1
        leather:
          price: 10
    6:
      icon: "iron_ingot"
      name: "Utils"
      required_to_move: 16
      items:
        iron_ingot:
          price: 4
        copper_ingot:
          price: 3
        gold_ingot:
          price: 10
        netherite_ingot:
          price: 500

Price_options:
  random_oscilation: true
  supply_and_demand: true

Market_control:
  taxation:
    # 5% taxation when players sell items.
    sell: 0.05
    # 5% taxation when players buy items.
    buy: 0.05
  high_market_control:
    enabled: true
    force_crash: false
    force_bullrun: false
    force_bull: true
    force_bear: true
  emergency_stop: true

Trading:
  enabled: true
  licence_price: 100000 # -1 means it cannot be purchased
  taxation:
    sell: 0.02
    buy: 0.02
  virtual_portfolio: true
  limited_orders: true
  stoploss: true