# Nascraft config.

# Check if the layout(s) required are present, and place them in case they are not.
AutoResourcesInjection: true

Items_quoted:
  Categories:
    # Num of the category. Categories are displayed in the main menu.
    1:
      icon: "cobblestone"
      # Name of the category.
      name: "Stone age"
      # Number of individual items needed to fluctuate the price. Adjust for volatility.
      required_to_move: 64
      items:
        # Items of the category
        cobblestone:
          # INITIAL price. This value will be ignored once the market starts developing his own valuations.
          price: 1
          # child items. The price of this items will be determined by his parent item and vice versa.
          child:
            cobblestone_stairs:
              # this option will set the price of cobblestone stairs at 1.5 * (price of cobblestone).
              linked: 1.5
            cobblestone_slab:
              linked: 0.5
            cobblestone_wall:
              linked: 1
        stone:
          price: 1.5
          child:
            stone_stairs:
              linked: 1.5
            stone_slob:
              linked: 0.5
            stone_pressure_plate:
              linked: 2
            stone_button:
              linked: 1
    2:
      icon: "redstone"
      name: "Tech"
      required_to_move: 16
      items:
        redstone:
          price: 2
          child:
            redstone_block:
              linked: 9


Price_options:
  random_oscilation: true
  supply_and_demand: true

Market_control:
  taxation:
    # 5% taxation when players sell items.
    sell: 0.05
    # 5% taxation when players buy items.
    buy: 0.05
  high_market_control:
    enabled: true
    force_crash: false
    force_bullrun: false
    force_bull: true
    force_bear: true
  emergency_stop: true

Trading:
  enabled: true
  licence_price: 100000 # -1 means it cannot be purchased
  taxation:
    sell: 0.02
    buy: 0.02
  virtual_portfolio: true
  limited_orders: true
  stoploss: true

Random_events:
  enabled: true
  1:
    text: "The FED (Federal Reserve of Diamonds) has announced a rise unprecedented of rates"
    effects: 1
    effect-1: "bear-2"
  2:
    text: "The ECB (European Crafting Bank) just announced a pack of measures to stimulate the economy"
    effects: 1
    effect-1: "bull-1"
  3:
    text: "One of the biggest financial companies just went bankrupt. How will the market react?"
    effects: 2
    effect-1: "bull-1"
    effect-2: "bear-2"

Text:
  enabled: true
  main_text: "Items Market"
  # Due high change in this text currently they won't be affected.
  buy: "BUY"
  sell: "SELL"
  hour: "hour"