# Nascraft config.yml - ${project.version}

# Language file to use. Available: en_US es_ES
language: 'en_US'

database:
  # Available types: SQLite
  type: 'SQLite'
  # How many days should logs of trades last in the database?
  # With the option 60, all trades older than 60 days will be automatically removed.
  # Use -1 to disable (Keep all trades logged).
  days-until-history-removed: 60

price-options:
  # Set (hard) limits on the minimum and maximum prices.
  limits:
    low: 0.001
    high: 9999999
  # With noise enabled, prices will vary over time in a pseudo-random manner.
  noise:
    enabled: true
    # Change the default intensity of the noise with this factor.
    default-intensity: 1
  # The default elasticity applies to all items unless otherwise explicitly stated at items.yml.
  default-elasticity: 1

market-control:
  # Although taxation gets applied for buying and selling actions separately, the total tax paid is the same regardless of how it is split
  # The spread is determined by the deviation in both actions. In the default case, it is 6% for selling and 4% for buying, resulting in a total spread of 10%.

  # To avoid strengthening the underground economy, try to keep the taxation as low as possible.
  # Heavy taxation can encourage players to trade with each other directly, bypassing intermediaries,
  # and reducing the amount of money collected from taxes and making the market less efficient.
  #
  # This value will be applied by default if no other tax is explicitly stated on the item at items.yml
  taxation:
    sell: 0.06 # 6% taxation when players sell items.
    buy: 0.04 # 4% taxation when players buy items.
  # Do players need the permission "nascraft.market" to operate directly with commands?
  market-permission: true

commands:
  # Available commands: sell, sellall, sellhand
  enabled:
    - 'sell'
    - 'sellall'
    - 'sellhand'
  sell-menu:
    size: 45
    help:
      enabled: true
      slot: 4
      texture: 'bc8ea1f51f253ff5142ca11ae45193a4ad8c3ab5e9c6eec8ba7a4fcb7bac40'
    filler:
      material: 'black_stained_glass_pane'
    sell-button:
      slot: 40
      material: 'yellow_stained_glass_pane'
    close-button:
      enabled: true
      slot: 8
      material: 'red_stained_glass_pane'

placeholders:
  # Number of decimals to display in prices.
  # For instance, with a price of 2.2732:
  # 1 -> 2.3$
  # 2 -> 2.27$
  # 3 -> 2.273$
  decimal-precision: 2

# FEATURE IN BETA AS OF ${project.version}
# Use with caution.
discord-bot:
  enabled: false
  token: 'TOKEN-ID'
  # Role requiered to execute admin commands through discord.
  # Current commands: /stop, /resume, /seeinv [ID], /seebal [ID]
  admin-role-id: 'ADMIN-ROLE-ID'
  # You can select a channel to send information of each transaction when executed.
  # You will most likely want to make the channel private, but it's optional.
  log-trades:
    enabled: false
    channel: 'LOGS-TEXTHANNEL-ID'
  # Menu to let users sell/buy items
  main-menu:
    enabled: false
    # Available methods: NATIVE, DISCORDSRV
    link-method: 'NATIVE'
    # This channel should be only used by the bot. Every message in it will be removed.
    channel: 'MAINMENU-TEXTCHANNEL-ID'
    # Default size of discord's virtual inventories.
    default-inventory: 5
    # Formula to calculate the price of then next slot. slot_price_factor * #slot + slot_price_base = price
    # For example, to buy the slot nº6 the price will be (1000 * 6) + 10000 = 16000$
    slot-price-factor: 1000
    slot-price-base: 10000
    in-game-gui:
      fillers:
        material: 'black_stained_glass_pane'
      locked:
        material: 'gray_stained_glass_pane'
      info:
        slot: 4
        texture: 'b722098ae79c7abf002fe9684c773ea71db8919bb2ef2053ea0c0684c5a1ce4f'
    # Discord taxes:
    taxation:
      override: true
      # By default, we apply a reduced tax to persuade users to operate through discord.
      buy: 0.04
      sell: 0.05
    options:
      # Button to access to the discord wiki.
      wiki:
        enabled: true
      # Both in-game commands and discord command/button.
      alerts:
        enabled: true
        # Time in days for alerts to expire.
        expiration: 10
      # Graphs of individual items (1 day, 1 month, 1 year, all)
      detailed-graphs:
        enabled: true
      # Access with the button to the personal log of trades.
      personal-log:
        enabled: true
      # Quick selection bar with the items of the main menu
      selection-bar:
        enabled: true
      # Button to generate a graph with the evolution of the CPI inside advanced options
      cpi:
        enabled: true

sell-wands:
  enabled: true
  wands:
    # ID - Just the identifier.
    basic:
      material: 'stick'
      # Recommended site to follow the format: https://webui.advntr.dev/
      display-name: '<b><gradient:#19e312:#a3e300>BASIC WAND</gradient></b>'
      lore:
        - '<b><gradient:#00eeff:#2e69ff>⏵ RIGHT CLICK</gradient></b> <color:#517d58>to estimate value.</color>'
        - '<b><gradient:#ff383b:#ff2403>⏵ LEFT CLICK</gradient></b> <color:#517d58>a container to</color>'
        - '<color:#517d58>sell all its content to the market!</color>'
        - ' '
        - '<color:#517d58>Uses left:</color> <b><color:#a3e300>[USES]</color></b>'
      # Maximum uses of the wand. Alternatively you can place a limit on
      # the quantity of the sells. See "MILLONAIRE WAND".
      # If you don't set any of these, the wand can be used without limits. (See "PERMANENT WAND").
      uses: 10
      # Permission to use this specific wand. If not defined, no permission will be required.
      permission: 'nascraft.wand.basic'

    permanent:
      material: 'blaze_rod'
      enchanted: true
      display-name: '<b><gradient:#e74cf5:#f51d41>PERMANENT WAND</gradient></b>'
      lore:
        - '<b><gradient:#00eeff:#2e69ff>⏵ RIGHT CLICK</gradient></b> <color:#8077ba>to estimate value.</color>'
        - '<b><gradient:#ff383b:#ff2403>⏵ LEFT CLICK</gradient></b> <color:#8077ba>a container to</color>'
        - '<color:#8077ba>sell all its content to the market</color>'
        - '<color:#8077ba>for <b><color:#ff2403>50%</color></b> of its value.</color>'
        - '<i><color:#343d66>⌛ 5 minutes of cooldown between uses.</color></i>'
        - ' '
        - '<b><gradient:#f51d41:#e74cf5>UNLIMITED USES</gradient><b>'
      multiplier: 0.5
      # Set a minimum cooldown between uses in seconds.
      cooldown: 300 # 300/60 = 5 min of cooldown.
      permission: 'nascraft.wand.advanced'

    millionaire:
      material: 'blaze_rod'
      enchanted: true
      display-name: '<b><gradient:#f57e00:#eff551>MILLIONARIE WAND</gradient></b>'
      lore:
        - '<b><gradient:#ff383b:#ff2403>⏵ LEFT CLICK</gradient></b> <color:#85784d>to estimate value.</color>'
        - '<b><gradient:#00eeff:#2e69ff>⏵ RIGHT CLICK</gradient></b> <color:#85784d>a container to</color>'
        - '<color:#85784d>sell all its content to the market</color>'
        - '<color:#85784d>for <color:#eff551>150%</color> its value.</color>'
        - ' '
        - '<color:#85784d>Left to sell:</color> <b><gradient:#eff551:#f57e00>[PROFIT-LEFT]</gradient></b>'
      # With this wand you can sell a maximum of 1.000.000$ (Including the multiplier) worth of items.
      max-profit: 1000000
      multiplier: 1.5
      permission: 'nascraft.wand.millonaire'
      # Change which click will be used to each action. Use 'none' to disable.
      # By default: sell: left estimate: right
      sell: 'right'
      estimate: 'left'

# Verify whether the AdvancedGUI's layout is present, and if it is not, place it in the layout folder of AdvancedGUI.
auto-resources-injection: true