# Nascraft config.

# Check if the layout(s) required are present, and place them in case they are not.
AutoResourcesInjection: true

Items_quoted:
  Categories:
    # Name of the category. Categories are displayed in the main menu.
    1:
      # Display-name of the category.
      name: "Stone age"
      items:
        # Items of the category
        cobblestone:
          # INITIAL price. This value will be ignored once the market starts developing his own valuations.
          price: 1
          # child items. The price of this items will be determined by his parent item and vice versa.
          child:
            cobblestone_stairs:
              # this option will set the price of cobblestone stairs at 1.5 * (price of cobblestone).
              linked: 1.5
            cobblestone_slab:
              linked: 0.5
            cobblestone_wall:
              linked: 1
        stone:
          price: 1.5
          child:
            stone_stairs:
              linked: 1.5
            stone_slab:
              linked: 0.5
            stone_pressure_plate:
              linked: 2
            stone_button:
              linked: 1
        cobbled_deepslate:
          price: 0.7
          child:
            cobbled_deepslate_stairs:
              linked: 1.5
            cobbled_deepslate_slab:
              linked: 0.5
            cobbled_deepslate_wall:
              linked: 1
    2:
      name: "Tech"
      items:
        redstone:
          price: 2
          child:
            redstone_block:
              linked: 9
        redstone_torch:
          price: 3
        repeater:
          price: 6
        comparator:
          price: 10
        piston:
          price: 9
        observer:
          price: 8
    3:
      name: "In the woods"
      items:
        oak_log:
          price: 1
          child:
            oak_planks:
              linked: 0.25
            oak_stairs:
              linked: 1.5
            oak_slab:
              linked: 0.5
            stick:
              linked: 0.0625
        birch_log:
          price: 1
          child:
            birch_planks:
              linked: 0.25
            birch_stairs:
              linked: 1.5
            birch_slab:
              linked: 0.5
            stick:
              linked: 0.0625
    4:
      name: "Valuables"
      items:
        diamond:
          price: 100
        emerald:
          price: 50
        raw_gold:
          price: 20
    5:
      name: "Utils"
      items:
        coal:
          price: 4
          child:
            charcoal:
              linked: 1
        leather:
          price: 10
    6:
      name: "Ingots"
      items:
        iron_ingot:
          price: 4
        copper_ingot:
          price: 3
        gold_ingot:
          price: 10
        netherite_ingot:
          price: 500

Price_options:
  random_oscilation: true
  supply_and_demand: true

Market_control:
  # Limit the precision of prices. With 2: the minimum price would be 0.01, with 3: 0.001 etc
  decimal_limit: 2
  # The spread is determined by the deviation in both actions. In the default case: 2% + 2% -> 4% of spread
  taxation:
    # 3% taxation when players sell items.
    sell: 0.02
    # 3% taxation when players buy items.
    buy: 0.02
  high_market_control:
    enabled: true
    # Wipe ~50% of the valuations in a couple movements.
    force_crash: false
    # Pump a ~50% of the valuations in minutes
    force_bullrun: false
    # Set the general tendency of the oscilations to positive.
    force_bull: true
    # Set the general tendency of the oscilations to negative.
    force_bear: true
  emergency_stop: true

Trading:
  enabled: true
  licence_price: 100000 # -1 means it cannot be purchased
  taxation:
    sell: 0.01
    buy: 0.01
  virtual_portfolio: true
  limited_orders: true
  stoploss: true

Lang:
  currency: "€"