name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.19
depend: [ AdvancedGUI, Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ bounser ]
description: Market valuations in minecraft
commands:
  nascraft:
