name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.13
depend: [ AdvancedGUI, Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ bounser ]
description: Market valuations in minecraft

commands:
  nascraft:
    description: Nascraft's admin command.
    aliases:
      - nc
  market:
    description: Interact with the market wherever you are!
    aliases:
      - mk
  sell:
    description: Sell items directly to the market
    aliases:
      - nsell

