name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.13
depend: [ Vault ]
softdepend: [ PlaceholderAPI, AdvancedGUI ]
authors: [ bounser ]
description: Market valuations in minecraft

commands:
  nascraft:
    description: Nascraft's admin command.
    aliases:
      - nc
  market:
    description: Interact with the market wherever you are!
    aliases:
      - mk
  sellhand:
    description: Sell items directly to the market
    aliases:
      - nsellhand
  sellall:
    description: Sell items directly to the market
    aliases:
      - nsellall
  sellinv:
    description: Sell items directly to the market
    aliases:
      - nsell
  link:
    description: Link accounts (Discord-Minecraft)
    aliases:
      - nlink
  setalert:
    description: Setup alerts
    aliases:
      - nsetalert
  alerts:
    description: View all alerts
    aliases:
      - nalerts
  discord:
    description: Discord command.
    aliases:
      - dis

